name: Fetch MPD

on:
  schedule:
    - cron: "0 */4 * * *"   # ogni 4 ore
  workflow_dispatch:

jobs:
  fetch_mpd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Fetch MPD
        run: node fetch_mpd.js

      - name: Commit MPD
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add main.mpd
          git commit -m "Updated MPD"
          git push
